### ISSUE TITLE
Feature Request: onSuccess prop for callback function upon successful swap

### ISSUE THREAD

**Issue by SamueleA** [Uniswap/widgets#11]
**Is your feature request related to a problem? Please describe.**
The widget does not give any indication of when a swap is successful. It would be useful to have a callback function of some kind being triggered once a swap is successful for closing a modal for example.

**Describe the solution you'd like**
A prop added added to the widget called `onSuccess` which is triggered upon successful swap.

**Describe alternatives you've considered**
I tried listening to events. However, this is overly complicated and also does not work perfectly because it's impossible to know exactly if the transaction that triggered the event is the same from the widget.
https://discord.com/channels/597638925346930701/941447445844463676/973999807737786398

**Additional context**
A PR was opened attempting to add this feature:
https://github.com/Uniswap/widgets/pull/10

**Comment by zzmp** [comment]
There is now an `onTxSuccess` callback.
