### ISSUE TITLE
Refactor exported `connections` to be within React lifecycle

### ISSUE THREAD

**Issue by NoahZinsmeister** [Uniswap/widgets#145]
Right now [`connections`](https://github.com/Uniswap/widgets/blob/133ed893c53a2edacb890ed5ecce53726a7fa0ce/src/hooks/connectWeb3/useWeb3React.tsx#L14) is statically exported and consumed by React components, but is itself modified within the React lifecycle.

Suggested fix would be to bring `connections` within React lifecycle and not statically export it.

**Comment by zzmp** [comment]
Fixed in #194.
