### ISSUE TITLE
NextJS "Window Not Defined" Error

### ISSUE THREAD

**Issue by akarys92** [Uniswap/widgets#146]
**Bug Description**
NextJS sometimes does server side rendering which does not have access to a 'window' object causing the app to crash before even loading. Seems to be stemming from [here](https://github.com/Uniswap/widgets/blob/ebe37e65ac98b50a04fcb1d9c9e8df820a851046/src/polyfills.ts)

**Steps to Reproduce**
Since it's hard to control when NextJS renders server side, this is somewhat intermittent but generally:
1. Create a new NextJS project
2. Import and insert the `<SwapWidget />` component
3. Reload the page
4. Note that the page does not even load and the app crashes with the error: 
```Server Error ReferenceError: window is not defined. This error happened while generating the page. Any console logs will be displayed in the terminal window.``` 

**Expected Behavior**
The page should load with the swap widget

**Additional Context**
https://github.com/Uniswap/widgets/blob/ebe37e65ac98b50a04fcb1d9c9e8df820a851046/src/polyfills.ts

**Comment by slavanga** [comment]
@akarys92 also see: https://github.com/Uniswap/widgets/issues/133
