### ISSUE TITLE
Add typing for the "data" field returned by callback functions such as onTxSuccess

### ISSUE THREAD

**Issue by SamueleA** [Uniswap/widgets#148]
**Is your feature request related to a problem? Please describe.**
It is difficult to work wit the `data` field returned by callback functions of the widget such as the `onTxSuccess` prop.
In effect, this field as data type `any` making is not idea to work with Typescript.

```
(txHash: string, data: any) => void
```

Furthermore, I ran into the issue that I wanted to know the type of transaction that triggered the `onTxSuccess`callback (SWAP, APPROVE or WRAP). Since there wasn't any Typescript type associated with the data field, I had to dig into the widget's code to be able to interpret the meaning of the `type` field. In this case, the type field was an enum called TransactionType, which is impossible to interpret without the type.

**Describe the solution you'd like**
I would like the `data` field to be fully typed for Typescript. Also, I would like every type used by that field to be exported so I can reference them in my app such as the `TransactionType`

**Comment by zzmp** [comment]
Fixed in #176.
