### ISSUE TITLE
Widget tries all RPC endpoints unnecessarily

### ISSUE THREAD

**Issue by superMDguy** [Uniswap/widgets#169]
**Bug Description**
When I open the Uniswap widget, it makes a bunch of requests to JSON RPC endpoints for different chains, instead of just the chain set by the wallet provider.

**Steps to Reproduce**

1. Open the widget
2. Check the network tab

**Expected Behavior**
The widget only uses RPC endpoints when it needs to access that chain

**Additional Context**
Digging into it some more, this happens because the `getBestUrl` function tries the default endpoints with multiple options:
https://github.com/Uniswap/web3-react/blob/main/packages/walletconnect/src/utils.ts.

Maybe it'd be best to only call `getBestUrl` when a given chain is needed?

**Comment by slavanga** [comment]
Also related: The widget tries to reach an endpoint for kovan (`https://kovan.poa.network/`) that does not exist anymore.

<img width="481" alt="Bildschirmfoto 2022-08-25 um 09 25 52" src="https://user-images.githubusercontent.com/1077807/186601992-7c3f7a3a-680a-4859-a64b-00291199794d.png">

**Comment by zzmp** [comment]
Fixed in #201.
Removing kovan.poa.network in #206.
