### ISSUE TITLE
Wrap action from ETH -> WETH perpetually shows "Fetching best price..."

### ISSUE THREAD

**Issue by undfined** [Uniswap/widgets#26]
**Bug Description**
Wrap action for ETH -> WETH perpetually shows "Fetching best price..."

![image](https://user-images.githubusercontent.com/954432/171951237-6a2cd0ab-39cf-4dba-804e-902164328a03.png)

**Steps to Reproduce**

1) Render widget 
2) Select ETH -> WETH 
3) Loader and "Fetching best price..." shown into perpetuity
   ...

**Expected Behavior**
No best price loader or value to be shown as it confuses the user, especially in the case where they lack the input amount in their wallet and thus they get a loader and less than obvious "balance too low" message:

![image](https://user-images.githubusercontent.com/954432/171951586-6d18ba1e-9c3c-4378-965a-bad1d3de8699.png)

**Comment by zzmp** [comment]
This should be fixed.
