### ISSUE TITLE
Unable to use Widget without unsafe-eval CSP 

### ISSUE THREAD

**Issue by niratodev** [Uniswap/widgets#51]
**Bug Description**
Uniswap's dependency AJV attempts to inject a script inline requiring `unsafe-eval`.

**Steps to Reproduce**
(Example, Next JS)

1. Disabling `unsafe-eval` or adding specific Content Security Policies for `script-src`
2. App will throw an error

<img width="828" alt="image" src="https://user-images.githubusercontent.com/73018676/177369448-5dd940df-b736-4ff6-9c20-6792c9497f94.png">

**Expected Behavior**
The ability to use the widget in a more secure environment.

**Additional Context**
[AJV's documentation](https://ajv.js.org/security.html#content-security-policy) recommends compiling using CLI or including it in the build.

**Comment by niratodev** [comment]
[Reproduced by forking the Uniswap Widget example](https://github.com/niratodev/uniswap-ajv-csp-demo/tree/uniswap-ajv-example)

Only change made is [adding a CSP rule](https://github.com/niratodev/uniswap-ajv-csp-demo/blob/uniswap-ajv-example/next.config.js)

**Comment by zzmp** [comment]
#134 was rolled back due to runtime breakages

**Comment by cmcewen** [comment]
released in https://github.com/Uniswap/widgets/releases/tag/v2.16.0
