### ISSUE TITLE
GetQuote failed on client: Error: Failed to get gas constants data from the optimism gas oracle

### ISSUE THREAD

**Issue by BenAzlay** [Uniswap/widgets#637]
On Base, when selecting ETH as the input token and USDC as the output token, and entering an amount of either ETH or USDC, it fails to estimate the corresponding amount of the other token. It shows the error "Error fetching trade" in the UI.

![Screenshot from 2024-07-19 11-28-11](https://github.com/user-attachments/assets/7dfcf7f4-0a7d-416c-81a8-016f64179de4)

In the console, it prints the following warning in a loop:
`GetQuote failed on client: Error: Failed to get gas constants data from the optimism gas oracle`
(Note that I am not on Optimism.)

![Screenshot from 2024-07-19 11-31-24](https://github.com/user-attachments/assets/10408912-f59e-4ba1-894a-0cba650e3b37)

My @uniswap/widgets version is 2.59.0.

**Comment by godsflaw** [comment]
I just hit this as well.

**Comment by BenAzlay** [comment]
Thanks to @umarsa, I managed to fix this issue by setting the routeUrl param to "https://api.uniswap.org/v1/" as in [Uniswap's own deployed example](https://widgets-uniswap.vercel.app/?fixtureId=%7B%22path%22%3A%22src%2Fcosmos%2FSwap.fixture.tsx%22%2C%22name%22%3Anull%7D).

It looks like:
```
<SwapWidget
              tokenList={'https://ipfs.io/ipns/tokens.uniswap.org'}
              width="100%"
              routerUrl="https://api.uniswap.org/v1/"
              brandedFooter={false}
 />
```

**Comment by Almuhanad-1** [comment]
> Thanks to [@umarsa](https://github.com/umarsa), I managed to fix this issue by setting the routeUrl param to "https://api.uniswap.org/v1/" as in [Uniswap's own deployed example](https://widgets-uniswap.vercel.app/?fixtureId=%7B%22path%22%3A%22src%2Fcosmos%2FSwap.fixture.tsx%22%2C%22name%22%3Anull%7D).
> 
> It looks like:
> 
> ```
> <SwapWidget
>               tokenList={'https://ipfs.io/ipns/tokens.uniswap.org'}
>               width="100%"
>               routerUrl="https://api.uniswap.org/v1/"
>               brandedFooter={false}
>  />
> ```

I faced the same issue and solved  by setting the routeUrl param to "https://api.uniswap.org/v1/" as you did and adding permit2={true}
it works fine in local but I get cors error on server

did you face the same issue? if yes how did you fix it?

note: I am using the latest version of the widget on a nextjs project

**Comment by umarsa** [comment]
We decided to take a different approach, but I think one way we addressed this during testing was to write a reverse proxy.
