### ISSUE TITLE
ConvenienceFee not working

### ISSUE THREAD

**Issue by eneasa** [Uniswap/widgets#9]
**Bug Description**
Updating the convenienceFeeRecipient and convenienceFee properties in the Swap component doesn't work and it does not transfer the tokens.

**Steps to Reproduce**
update convenienceFeeRecipient and convenienceFee in Swap component to a valid address and a number between 0 and 100

**Expected Behavior**
with convenienceFee = 100 there should be a 1% transfer made to the convenienceFeeRecipient address. If the transfer is 100 tokens, 1 should be transferred to convenienceFeeRecipient. 

**Additional Context**
This works well in the Widget but not in the interface

**Comment by willhennessy** [comment]
A second report on twitter https://twitter.com/cryptodave__/status/1523490697860452353?s=21&t=KY8LgRZjyrqP5WnEUEeQKw

Zach can you investigate?

**Comment by eneasa** [comment]
Thank you willhennessy and zzmp,

See more details below

The Swap component has the properties for convenienceFee and convenienceFeeRecipient. 
Setting values in the Swap component to convenienceFee=100 and convenienceFeeRecipient=<a valid address> does not transfer 1% of the total tokens in the final transaction to the fee recipient.

As an example, if we set those values in the widget the final transaction transfers 1% of the total tokens to the  convenienceFeeRecipient address as a few for the swap.

I can also see useSyncTokenDefaults hook under lib/hooks/swap but it doesn't seem to be called

how can we make sure if we set those values the fee gets executed as part of the transaction?

**Comment by haggisswap** [comment]
Hi @zzmp  @willhennessy 

Just realised you've transferred the issue to the Widgets repo. 
This issue is only happening in the interface repository.

In the "widgets repo" the convenienceFee and convenienceFeeRecipient work as expected.

It's only when you set values for convenienceFee and convenienceFeeRecipient under the "Swap" component in the interface repository when it doesn't work

Hope it helps

**Comment by eneasa** [comment]
Hey @zzmp 

Closing this issue as the Fee is working in the widget.
this feature is missing from the interface.

Regards
